# Generated by Django 2.2.9 on 2020-06-03 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produits',
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caisse.Produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
